version: 0.2

phases:
  build:
    commands:
      - echo "Zipping source..."
      - zip -r app.zip . -x "*.git*" "node_modules/*" "*.log"
      - echo "Uploading and deploying..."

      - bash -c "
          set -e
          TIMESTAMP=\$(date +%s)
          S3_KEY=app-\$TIMESTAMP.zip
          VERSION_LABEL=ver-\$TIMESTAMP

          echo 'Zipping app and uploading to S3...'
          aws s3 cp app.zip s3://eb-deploy-bucket-bonny/\$S3_KEY

          echo 'Creating EB application version...'
          aws elasticbeanstalk create-application-version \
            --application-name my-first-Elastic-beanstalk-webapp \
            --version-label \$VERSION_LABEL \
            --source-bundle S3Bucket=eb-deploy-bucket-bonny,S3Key=\$S3_KEY

          echo 'Deploying new version to Elastic Beanstalk...'
          aws elasticbeanstalk update-environment \
            --environment-name My-first-Elastic-beanstalk-webap-env \
            --version-label \$VERSION_LABEL
        "

