version: 0.2

phases:
  build:
    commands:
      - echo "Zipping source..."
      - zip -r app.zip . -x "*.git*" "node_modules/*" "*.log"
      - echo "Uploading and deploying..."
      - |
        bash -c '
          TIMESTAMP=$(date +%s);
          S3_KEY=app-$TIMESTAMP.zip;
          VERSION_LABEL=ver-$TIMESTAMP;
        
          echo "Uploading to S3: $S3_KEY";
          aws s3 cp app.zip s3://eb-deploy-bucket-bonny/$S3_KEY;
        
          echo "Creating Elastic Beanstalk app version: $VERSION_LABEL";
          aws elasticbeanstalk create-application-version \
            --application-name my-first-Elastic-beanstalk-webapp \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket=eb-deploy-bucket-bonny,S3Key=$S3_KEY;
        
          echo "Updating Elastic Beanstalk environment";
          aws elasticbeanstalk update-environment \
            --environment-name My-first-Elastic-beanstalk-webap-prod \
            --version-label $VERSION_LABEL;
        '
